version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g serverless@2.72.4
      - npm install
      - sls -v
  build:
    commands:
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY_ID
      - serverless deploy --stage dev --region ap-south-1

cache:
  paths:
    - node_modules